name: ".NET Framework 4.8 Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        shell: pwsh
        run: |
              nuget restore "Prog6221_ST10438702_part1_poe.csproj"

      - name: Build with MSBuild
        shell: pwsh
        run: |
            msbuild "Prog6221_ST10438702_part1_poe.csproj" `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:OutputPath="Prog6221_ST10438702_part1_poe\bin\Release"



     

     
  
