name: .NET Framework 4.8 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore packages
        run: nuget restore CyberSecruityHelpChatBotPoe.csproj

      - name: Build solution
        run: msbuild CyberSecruityHelpChatBotPoe.csproj /p:Configuration=Release /p:Platform="Any CPU"

     

     
  
