name: ".NET Framework 4.8 Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CyberSecruityHelpChatBotPoe.csproj -SolutionDirectory .

      - name: Build with MSBuild
        run: msbuild CyberSecruityHelpChatBotPoe.csproj /p:Configuration=Release /p:Platform="Any CPU"
    
   


     

     
  
